<?php

declare(strict_types=1);

return [
    'directories' => [
        '.build',
        '.ddev',
        '.git',
        '.github',
        'bin',
        'build',
        'public',
        'Resources/Private/JavaScript',
        'tailor-version-upload',
        'Tests',
        'var',
        'vendor',
    ],
    'files' => [
        'DS_Store',
        'CODE_OF_CONDUCT.md',
        'codeception.yml',
        'codecov.yml',
        'CODEOWNERS',
        'composer.lock',
        'CONTRIBUTING.md',
        'crowdin.yaml',
        'dependency-checker.json',
        'docker-compose.yml',
        'editorconfig',
        'editorconfig-lint.php',
        'gitattributes',
        'gitignore',
        'packaging_exclude.php',
        'php-cs-fixer.php',
        'phpstan.neon',
        'phpstan-baseline.neon',
        'phpunit.functional.xml',
        'phpunit.unit.xml',
        'rector.php',
        'renovate.json',
        'typoscript-lint.yml',
    ],
];
