name: Build and release TYPO3 extension
on:
  push:
    branches:
      - develop

jobs:
  release:
    if: github.ref == 'refs/heads/develop'
    uses: maikschneider/reusable-workflows/.github/workflows/release-typo3-extension.yml@main
    secrets:
      teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
    with:
      base-branch: master

  release-v3:
      if: github.ref == 'refs/heads/v3.x-dev'
      uses: maikschneider/reusable-workflows/.github/workflows/release-typo3-extension.yml@main
      secrets:
          teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
      with:
          base-branch: v3.x
